package constants

var (
	DashboardRoute              = "/dashboard"
	DashboardMessageRoute       = "/messages"
	DashboardNotificationsRoute = "/notifications"
	DashboardPaymentsRoute      = "/payments"
	DashboardUsersRoute         = "/users"
	MealsKey                    = "meals"
	EventsKey                   = "events"
	MessageKey				  	= "messages"
	UserKeyPrefix               = "user-"
	SermonKeyPrefix             = "sermon-page-"
	StripeCustomerRoute         = "/customers?"
	StripeEphemeralKeyRoute     = "/ephemeral_keys?"
	StripePaymentIntentRoute    = "/payment_intents?"
	FirebaseServiceTokenKey     = "firebase"
	AllUsersTopic               = "all-users"
	RedisURL                    = "redis://default:1bfa8d44dbad46aeb928cd82cfc61f62@enabling-elephant-37354.upstash.io:37354"
	PlannnigCenterUrl			= "https://api.churchcenter.com/calendar/v2/events"
	PlannnigCenterTokenUrl		= "https://momentumlifegroups.churchcenter.com/sessions/tokens"
	TokenKey  					= "planning-token"
	Admin 						= "admin"
	Header 						= "header"
	Message 					= "message" 
)
